-- Generated by nwg-displays on 2026-06-05 at 21:10:27. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "840x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "eDP-1",
    disabled = true
})
