#!/bin/bash

set -e

SESSION="code"
PROJECT="$HOME/Workspace"

# -----------------------------
# NVIM IDE
# ----------------------------
ghostty -e nvim "$PROJECT" &

# -----------------------------
# TMUX Session
# ----------------------------
ghostty -e tmux new -A -s $SESSION -c $PROJECT &
tmux neww -t "$SESSION" -n "servers" &
tmux splitw -v -t "$SESSION" &

# -----------------------------
# Git Sessions
# ----------------------------
ghostty --working-directory="$PROJECT" &

# -----------------------------
# Yazi
# ----------------------------
ghostty -e yazi
