#!/bin/zsh

set -e 

CHATGPT="https://chatgpt.com"
DOCS_LARAVEL="https://laravel.com/docs/13.x"

launch_obsidian(){
   flatpak run md.obsidian.Obsidian \
  "obsidian://open?vault=notes" & 
}

launch_browser(){
    brave --new-window "$CHATGPT" &
    brave --new-tab "$DOCS_LARAVEL" &
  }

main(){
    launch_obsidian
    launch_browser
}

main
