#!/bin/zsh

set -e

SESSION="system"

create_tmux_session(){
  if tmux has-session -t "$SESSION" 2>/dev/null; then
    return
  fi  

  tmux new-session -d -s "$SESSION" -n "system"
  tmux split-window -v -t "$SESSION":system
  tmux send-keys -t "$SESSION":system.1 "btop" C-m
  tmux send-keys -t "$SESSION":system.0 "fastfetch" C-m 
}

launch_tmux(){
  ghostty -e tmux attach-session -t "$SESSION" &
}

main() {
  create_tmux_session
  launch_tmux
}

main
